In [3]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model


### y = 3x_1 - 2x_2 + 1 のデータを作成

x1 = np.random.rand(100, 1)  # 0 〜 1 までの乱数を 100 個つくる
x1 = x1 * 4 - 2              # 値の範囲を -2 〜 2 に変更

x2 = np.random.rand(100, 1)  # x2 についても同様
x2 = x2 * 4 - 2

y = 3 * x1 - 2 * x2 + 1


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
model.coef_

array([[ 3., -2.]])

In [9]:
model.intercept_

array([1.])

In [10]:
x1_x2

array([[ 0.9793336 ,  0.62755066],
       [-1.1931272 , -0.34546965],
       [-0.11076189, -1.46245666],
       [ 0.82218952,  1.28038772],
       [-1.20356733,  1.16691726],
       [-0.62797778, -0.89050063],
       [ 0.42153008, -1.15175827],
       [-0.10204653,  1.55554626],
       [-0.16439644,  1.46942173],
       [-1.25834294, -1.23132548],
       [-1.89932776,  1.31882935],
       [-1.56405317,  0.8828741 ],
       [-0.23152053,  0.26442473],
       [ 0.6919826 ,  1.25801691],
       [-0.58106969, -1.38311601],
       [ 0.94567622,  1.21121967],
       [-0.19199234,  1.64605215],
       [-0.45764423,  0.88203358],
       [-0.27766725, -1.71810691],
       [-1.56105062, -1.00314855],
       [-0.93080213, -1.9818701 ],
       [-0.45863499, -0.53797485],
       [-0.38202534, -0.04574313],
       [-1.63495991,  1.25945035],
       [ 0.61116329, -1.16718848],
       [ 1.46122514,  0.01105302],
       [-0.39389748,  0.73481165],
       [-1.22695887, -0.64367565],
       [-1.80961153,