In [64]:
import numpy as np

In [65]:
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [66]:
X = np.array([[1,2], [3,4]])
print(X)

[[1 2]
 [3 4]]


In [67]:
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [68]:
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [69]:
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [70]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [71]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


In [72]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [73]:
XtX_inv =np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [74]:
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [75]:
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [76]:
import sklearn

In [77]:
from sklearn.linear_model import LinearRegression

In [78]:
model = LinearRegression()

In [79]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [80]:
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [81]:
model.intercept_

array([-0.14285714])

In [82]:
model.score(X,y)

0.6923076923076923

In [83]:
x = np.array([[1,2,3]])

In [84]:
y_pred = model.predict(x)
y_pred

array([[3.]])